# Este notebook será usado para testar algumas funções de pytorch, principalmente aquelas que fazem transformação no formato dos dados

In [1]:
import torch

In [22]:
lista = [1, 2, 3, 4, 5]
x = torch.Tensor(lista)

x

tensor([1., 2., 3., 4., 5.])

Muda o shape de x para adicionar uma nova dimensão na posição 0, e coloca todos os valores do tensor nessa nova dimensão
A dimensão 0 é a dimensão das colunas

In [23]:
x_0 = x.unsqueeze(0)
x_0

tensor([[1., 2., 3., 4., 5.]])

Muda o shape de x para adicionar uma nova dimensão na posição 1, e coloca todos os valores do tensor nessa nova dimensão
A dimensão 0 é a dimensão das linhas

In [24]:
x_1 = x.unsqueeze(1)
x_1

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

Muda o shape de x removendo a dimensão extra adicionada nos eixos 0 e 1

In [38]:
original_x_1 = x_1.squeeze(1)
original_x_0 = x_0.squeeze(0)
original_x_1, original_x_0

(tensor([1., 2., 3., 4., 5.]), tensor([1., 2., 3., 4., 5.]))