# Debug pipeline para select_action()
Use este notebook para montar um estado sintético, rodar `select_action()` e inspecionar as saídas.

In [8]:
import torch

from ai import Dqn

torch.manual_seed(0)

input_size = 5
nb_action = 3
gamma = 0.9

dqn = Dqn(input_size=input_size, nb_action=nb_action, gamma=gamma)

state = torch.randn(1, input_size)
state

tensor([[ 1.3615,  0.8063, -1.7691, -0.9467,  0.4066]])

In [20]:
actions = [dqn.select_action(state, debug = True) for i in range(5)]
actions

/home/mileguir/Desktop/curso-aprendizado-por-reforco-udemy/Carro_autonomo/ai.py:129: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  state_tensor = torch.tensor(state, dtype=torch.float32).to(self.device)




action:

tensor([0], device='cuda:0')


action:

tensor([0], device='cuda:0')


action:

tensor([1], device='cuda:0')


action:

tensor([0], device='cuda:0')


action:

tensor([0], device='cuda:0')


[tensor(0, device='cuda:0'),
 tensor(0, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(0, device='cuda:0'),
 tensor(0, device='cuda:0')]