# Debug pipeline para learn()
Este notebook cria dados sinteticos e roda `learn(..., debug=True)` para inspecionar os valores intermediarios.

In [6]:
import torch

from ai import Dqn

torch.manual_seed(0)

input_size = 5
nb_action = 3
gamma = 0.9
batch_size = 4

dqn = Dqn(input_size=input_size, nb_action=nb_action, gamma=gamma)

batch_state = torch.randn(batch_size, input_size)
batch_next_state = torch.randn(batch_size, input_size)
batch_action = torch.randint(0, nb_action, (batch_size,), dtype=torch.long)
batch_reward = torch.randn(batch_size)

In [7]:
batch_state

tensor([[ 0.7073,  0.5800,  0.2683, -2.0589, -0.9801],
        [ 0.0605, -0.4890, -1.5771,  0.3609, -1.3533],
        [-0.2071, -0.2488, -0.6204,  0.9884, -0.4322],
        [-1.1187,  0.3784, -0.7804, -0.8739, -0.7328]])

In [8]:
batch_next_state

tensor([[-1.0715e+00, -1.1665e-01, -1.0170e+00, -1.4453e+00,  7.7037e-01],
        [ 3.9068e-01,  2.8959e-01, -2.7575e+00, -8.3236e-01,  4.8999e-01],
        [ 2.9082e-01,  6.4423e-01, -9.3218e-04, -1.6269e-01, -2.4772e-01],
        [ 2.4197e+00,  1.6456e+00, -3.0869e-01, -1.5147e+00,  1.9457e+00]])

In [9]:
batch_action

tensor([0, 1, 1, 2])

In [10]:
batch_reward

tensor([ 0.3106,  0.4142, -1.4562, -0.5476])

In [3]:
dqn.learn(
    batch_state=batch_state,
    batch_next_state=batch_next_state,
    batch_reward=batch_reward,
    batch_action=batch_action,
    debug=True,
)


outputs antes de .gather: tensor([[ 0.0556, -0.2976, -0.3212],
        [ 0.1067, -0.0029, -0.0761],
        [-0.1368, -0.1396,  0.0018],
        [ 0.1169, -0.1876, -0.2430]], grad_fn=<AddmmBackward0>)

outputs depois de .gather e antes de .squeeze(1): tensor([[ 0.0556],
        [-0.0029],
        [-0.1396],
        [-0.2430]], grad_fn=<GatherBackward0>)

batch_action sem unsqueeze(1): tensor([0, 1, 1, 2])

next_outputs antes de .detach(): tensor([[-0.0174,  0.0087, -0.1966],
        [ 0.0901,  0.2046, -0.1657],
        [ 0.0037, -0.2597, -0.0419],
        [ 0.1038, -0.1099, -0.2729]], grad_fn=<AddmmBackward0>)

next_outputs depois de .detach() e antes de .max(1)tensor([[-0.0174,  0.0087, -0.1966],
        [ 0.0901,  0.2046, -0.1657],
        [ 0.0037, -0.2597, -0.0419],
        [ 0.1038, -0.1099, -0.2729]])

next_outputs depois de .max(1)torch.return_types.max(
values=tensor([0.0087, 0.2046, 0.0037, 0.1038]),
indices=tensor([1, 1, 0, 0]))

next_outputs completo: tensor([0.0087, 0.2046