# Debug pipeline para learn()
Este notebook cria dados sinteticos e roda `sample()` para inspecionar o retorno

In [5]:
import torch

from ai import ReplayMemory

In [14]:
rm = ReplayMemory(5)

state1 = 1
state2 = 2
state3 = 3
state4 = 4

prev_states = [state1, state2, state3, state4]

state5 = 5
state6 = 6
state7 = 7
state8 = 8

next_states = [state5, state6, state7, state8]

action1 = 9
action2 = 10
action3 = 11
action4 = 12

actions = [action1, action2, action3, action4]

reward1 = 13
reward2 = 14
reward3 = 15
reward4 = 16

rewards = [reward1, reward2, reward3, reward4]

for index in range(4):
    prev_state = torch.tensor(prev_states[index], dtype=torch.float).unsqueeze(0)
    next_state = torch.tensor(next_states[index], dtype=torch.float).unsqueeze(0)
    action = torch.tensor(actions[index], dtype=torch.float).unsqueeze(0)
    reward = torch.tensor(rewards[index], dtype=torch.float).unsqueeze(0)

    rm.push((prev_state, next_state, action, reward))

iterator = rm.sample(3, debug=True)

print("\n")

for item in iterator:
    print(item)



Iteravel samples:

[(tensor([4.]), tensor([3.]), tensor([1.])), (tensor([8.]), tensor([7.]), tensor([5.])), (tensor([12.]), tensor([11.]), tensor([9.])), (tensor([16.]), tensor([15.]), tensor([13.]))]

Cada sample contido em samples:

(tensor([4.]), tensor([3.]), tensor([1.]))

(tensor([8.]), tensor([7.]), tensor([5.]))

(tensor([12.]), tensor([11.]), tensor([9.]))

(tensor([16.]), tensor([15.]), tensor([13.]))


tensor([4., 3., 1.])
tensor([8., 7., 5.])
tensor([12., 11.,  9.])
tensor([16., 15., 13.])
